### PR TITLE
Add more relevant information to the app settings page

### PR DESCRIPTION
**Pull request by leepeuker**

### CODE REVIEW

**Comment by JVT038** [comment]
Perhaps try to fetch the release notes for the current version and display that on the about page?

**Comment by leepeuker** [comment]
> Perhaps try to fetch the release notes for the current version and display that on the about page?

I think I would like to do it like overseerr, see here:

image

**Comment by JVT038** [comment]
Yeah, that would look good as well!

**Comment by leepeuker** [comment]
Current state here:

image

For adding releases to the settings page I have started https://github.com/leepeuker/movary/pull/299

**Comment by leepeuker** [comment]
There is still a bug in some text colors when changing themes, looking into it

**Pull request merged**
