### PR TITLE
Sort by watched

### LINKED ISSUE #444: feature - allow sort by watch date
add option to sorting type in 'all movies' to sort by the date that the movie was watched.

could be extended to actors/directors as a 'sort by last seen' or something like that

### PR DESCRIPTION
**Pull request by pbogre**
closes #444

added option in toggleSearchModal "SortBy" field to sort by `watched_at` value in database.

PS: sorry about the mess with the commits

### CODE REVIEW

**Comment by leepeuker** [comment]
> sorry about the mess with the commits

No problem ;)

**Comment by pbogre** [comment]
i really need to stop doing this 😂

**Comment by leepeuker** [comment]
Ah, this breaks with mysql 

```
[2023-07-26T19:43:06.268278+02:00] movary.EMERGENCY: An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'movary.mh.watched_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 1055): An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of ORDER BY clause is not in GROUP BY clause and contains nonaggregated column 'movary.mh.watched_at' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /app/vendor/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php:117)
[stacktrace]
#0 /app/vendor/doctrine/dbal/src/Connection.php(1935): Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter->convert(Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), Object(Doctrine\\DBAL\\Query))
#1 /app/vendor/doctrine/dbal/src/Connection.php(1878): Doctrine\\DBAL\\Connection->handleDriverException(Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), Object(Doctrine\\DBAL\\Query))
#2 /app/vendor/doctrine/dbal/src/Connection.php(1103): Doctrine\\DBAL\\Connection->convertExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDO\\Exception), 'SELECT m.*, mur...', Array, Array)
#3 /app/vendor/doctrine/dbal/src/Connection.php(899): Doctrine\\DBAL\\Connection->executeQuery('SELECT m.*, mur...', Array, Array)
#4 /app/src/Domain/Movie/MovieRepository.php(673): Doctrine\\DBAL\\Connection->fetchAllAssociative('SELECT m.*, mur...', Array)
#5 /app/src/Domain/Movie/History/MovieHistoryApi.php(309): Movary\\Domain\\Movie\\MovieRepository->fetchUniqueMoviesPaginated(1, 24, 1, '', 'watchDate', Object(Movary\\ValueObject\\SortOrder), NULL, '', '')
#6 /app/src/Domain/Movie/MovieApi.php(201): Movary\\Domain\\Movie\\History\\MovieHistoryApi->fetchUniqueMoviesPaginated(1, 24, 1, '', 'watchDate', Object(Movary\\ValueObject\\SortOrder), NULL, '', '')
#7 /app/src/HttpController/MoviesController.php(39): Movary\\Domain\\Movie\\MovieApi->fetchUniqueMoviesPaginated(1, 24, 1, '', 'watchDate', Object(Movary\\ValueObject\\SortOrder), NULL, '', '')
#8 [internal function]: Movary\\HttpController\\MoviesController->renderPage(Object(Movary\\ValueObject\\Http\\Request))
#9 /app/vendor/php-di/invoker/src/Invoker.php(74): call_user_func_array(Array, Array)
#10 /app/vendor/php-di/php-di/src/Container.php(248): Invoker\\Invoker->call(Array, Array)
#11 /app/public/index.php(41): DI\\Container->call(Array, Array)
#12 {main}
``

**Comment by pbogre** [comment]
hm, perhaps adding `watched_at` to the GROUP BY sql entry should suffice, ill do that now

**Pull request merged**
